# Generated by Django 3.0.7 on 2020-06-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateTimeField(verbose_name='measure date')),
                ('measure_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
