# Generated by Django 3.0.7 on 2020-06-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measure_rate',
            field=models.IntegerField(),
        ),
    ]
