# Generated by Django 3.0.7 on 2020-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200624_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_rate',
            field=models.FloatField(),
        ),
    ]
